# Generated by Django 4.2.2 on 2024-06-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bduSuport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicLevels',
            new_name='AcademicLevel',
        ),
        migrations.RenameModel(
            old_name='EvaluationMethods',
            new_name='EvaluationMethod',
        ),
        migrations.RenameModel(
            old_name='Majors',
            new_name='Major',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
