student_key_mapping = {
    "cccd": "id_card",
    "created_at": "created_at",
    "dan_toc": "ethnicity",
    "email": "email",
    "gioi_tinh": "gender",
    "hien_dien": "attendance",
    "ho_khau": "residence",
    "ho_sv": "last_name",
    "ma_chuyen_nganh": "major_code",
    "ma_cvht": "advisor_code",
    "ma_he_dao_tao": "education_system_code",
    "ma_khoa": "faculty_code",
    "ma_lop": "class_code",
    "ma_nganh": "field_code",
    "mssv": "student_id",
    "ngay_sinh": "date_of_birth",
    "nguon": "source",
    "nk": "academic_year",
    "noi_sinh": "place_of_birth",
    "sdt": "phone_number",
    "ten_bac_hoc": "degree_name",
    "ten_chuyen_nganh": "major_name",
    "ten_cvht": "advisor_name",
    "ten_day_du": "full_name",
    "ten_khoa": "faculty_name",
    "ten_lop": "class_name",
    "ten_nganh": "field_name",
    "ten_sv": "first_name",
    "ton_giao": "religion",
    "updated_at": "updated_at"
}

attendance_key_mapping = {
    "buoi": "lesson",
    "created_at": "created_at",
    "diem_danh": "status",
    "ma_diem_danh": "attendance_id",
    "ma_mon_hoc": "subject_code",
    "ten_mon_hoc": "subject_name",
    "ma_nhom": "group_code",
    "mssv": "student_code",
    "ngay": "attendance_datetime",
    "ngay_origin": "attendance_date",
    "updated_at": "updated_at"
}